apiVersion: v1
kind: Pod
metadata:
  name: rockstar-dotnet-webapi
  labels:
    app: rockstar-dotnet-webapi
spec:
  containers:
    - image: deep2105/rockstar-dotnet-webapi
      name: rockstar-dotnet-webapi
      ports:
        - containerPort: 80