apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rockstar-react-fe 
spec:
  selector:
    matchLabels:
      app: rockstar-react-fe
  replicas: 3 
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: rockstar-react-fe
    spec:
      containers:
        - image: deep2105/rockstar-react-fe:minikube
          imagePullPolicy: Always
          name: rockstar-react-fe 
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rockstar-react-fe-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: rockstar-react-fe